name: "Neon Database Delete Branch by name"
author: "Neon Database"
description: "Deletes Neon Postgres branch by name"
branding:
  icon: "box"
  color: "red"

inputs:
  project_id:
    required: true
    type: string
  branch_name:
    required: true
    type: string
  api_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Search branch by name
      id: get_branch_id
      run: |
        branch_id=$(curl --silent \
          "https://console.neon.tech/api/v2/projects/${PROJECT_ID}/branches" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${API_KEY}" \
          | jq -r .branches \
          | jq -c '.[] | select(.name | contains("'${BRANCH_NAME}'")) .id' \
          | jq -r \
          ) \
        echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT
        
      env:
        PROJECT_ID: ${{ inputs.project_id }}
        API_KEY: ${{ inputs.api_key }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v2
        with:
          project_id: ${{ inputs.project_id }}
          branch_id: ${{ steps.get_branch_id.outputs.branch_id }}
          api_key: ${{ inputs.api_key }}
